#Database for all the application paths that are on the machine

application_name = {}
app_location = {}
print("hello world")

application_name[1] = "Chrome"
application_name[2] = "Command Line"
application_name[3] = "Discord"
application_name[4] = "Excel"
application_name[5] = "File Explorer"
application_name[6] = "HearthStone"
application_name[7] = "Illustrator"
application_name[8] = "InDesign"
application_name[9] = "Minecraft"
application_name[10] = "Photoshop"
application_name[11] = "PowerPoint"
application_name[12] = "Premiere Pro"
application_name[13] = "Starcraft"
application_name[14] = "Steam"
application_name[15] = "Spotify"
application_name[16] = "Visual Studio"
application_name[17] = "Word"

app_location[1] = "chrome.exe"
app_location[2] = "C:\\Users\\Nkitc\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\System Tools\\Command Prompt"
app_location[3] = "C:\\Users\\Nkitc\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Discord Inc\\Discord"
app_location[4] = ""
app_location[5] = ""
app_location[6] = "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Hearthstone\\HearthStone"
app_location[7] = ""
app_location[8] = ""
app_location[9] = ""
app_location[10] = ""
app_location[11] = ""
app_location[12] = ""
app_location[13] = ""
app_location[14] = ""
app_location[15] = ""
app_location[16] = ""
app_location[17] = "C:\Program Files\WindowsApps\Microsoft.Office.Desktop.Word_16051.12827.20268.0_x86__8wekyb3d8bbwe\Office16\\WINWORD.EXE"