#Database for all the application paths that are on the machine

application_name = {}
app_location = {}

application_name[1] = "Chrome"
application_name[2] = "Command Line"
application_name[3] = "Discord"
application_name[4] = "File Explorer"
application_name[5] = "HearthStone"
#application_name[6] = "Illustrator"
#application_name[7] = "InDesign"
application_name[8] = "iTunes"
application_name[9] = "Minecraft"
application_name[10] = "Photoshop"
application_name[11] = "Premiere Pro"
application_name[12] = "Starcraft"
application_name[13] = "Steam"
application_name[14] = "Spotify"
application_name[15] = "Visual Studio"
application_name[16] = "Word"

app_location[1] = "chrome.exe"
app_location[2] = "C:\\Users\\Nkitc\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\System Tools\\Command Prompt"
app_location[3] = "C:\\Users\\Nkitc\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Discord Inc\\Discord"
app_location[4] = "C:\\Users\\Nkitc\\Documents"
app_location[5] = "C:\\Program Files (x86)\\Hearthstone\\Hearthstone Beta Launcher.exe"
#app_location[6] = ""
#app_location[7] = ""
app_location[8] = "C:\\Users\\Nkitc\\AppData\\Local\\Microsoft\\WindowsApps\\iTunes.exe"
app_location[9] = "C:\\Program Files (x86)\\Minecraft Launcher\\MinecraftLauncher.exe"
app_location[10] = "C:\\Program Files\\Adobe\\Adobe Photoshop 2020\\Photoshop.exe"
app_location[11] = "C:\\Program Files\\Adobe\\Adobe Premiere Pro 2020\\Adobe Premiere Pro.exe"
app_location[12] = "C:\\Program Files (x86)\\StarCraft II\\StarCraft II.exe"
app_location[13] = "C:\\Program Files (x86)\\Steam\\steam.exe"
app_location[14] = "C:\\Users\\Nkitc\\AppData\\Roaming\\Spotify\\Spotify.exe"
app_location[15] = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe"
app_location[16] = "C:\\Users\\Nkitc\\AppData\\Local\\Microsoft\\WindowsApps\\winword.exe"